# do not use "latest" here, if you want this to work in the future
default:
  image: ubuntu:20.04
  tags:
    - shell-runner

stages:
  - build
  - test
  - deploy

# Use this if your GitLab runner does not use socket binding
# services:
#   - docker:dind

before_script:
  - echo -n $DOCKER_REGISTRY_TOKEN | docker login -u $DOCKER_REGISTRY_USER --password-stdin $DOCKER_REGISTRY

#  - docker login -u $DOCKER_REGISTRY_USER -p $DOCKER_REGISTRY_TOKEN $DOCKER_REGISTRY

###############################################
###               SCHEDULE                  ###
###############################################

Build_Base:on-schedule:
  stage: build
  rules:
    - if: $S_WEEKLY == "schedule"
  script:
    - docker pull $DOCKER_REGISTRY_IMAGE:nest-simulator-build-base || true
    - docker pull $DOCKER_REGISTRY_IMAGE:nest-simulator-deploy-base || true
    - docker build
      --file src/base/Dockerfile-build-base
      --cache-from $DOCKER_REGISTRY_IMAGE:nest-simulator-build-base
      --tag $DOCKER_REGISTRY_IMAGE:nest-simulator-build-base
      .
    - docker push $DOCKER_REGISTRY_IMAGE:nest-simulator-build-base
    - docker build
      --file src/base/Dockerfile-deploy-base
      --cache-from $DOCKER_REGISTRY_IMAGE:nest-simulator-deploy-base
      --tag $DOCKER_REGISTRY_IMAGE:nest-simulator-deploy-base
      .
    - docker push $DOCKER_REGISTRY_IMAGE:nest-simulator-deploy-base
  tags:
    - shell-runner

###############################################
###               DEV                       ###
###############################################

Build_Dev:
  stage: build
  script:
    - docker pull $DOCKER_REGISTRY_IMAGE:dev || true
    - docker build 
        --cache-from $DOCKER_REGISTRY_IMAGE:dev
        --tag $DOCKER_REGISTRY_IMAGE:dev.$CI_PIPELINE_ID 
        ./src/dev  
    - docker push $DOCKER_REGISTRY_IMAGE:dev.$CI_PIPELINE_ID
  tags:
    - shell-runner

Test_Dev:
  stage: test
  needs: ["Build_Dev"]
  script:
    - docker pull $DOCKER_REGISTRY_IMAGE:dev.$CI_PIPELINE_ID
    - docker ps
    - docker run -i -d --rm -e NEST_CONTAINER_MODE=nest-server -p 5000:5000  
        --name $CI_PIPELINE_ID $DOCKER_REGISTRY_IMAGE:dev.$CI_PIPELINE_ID
    - docker ps
  tags:
    - shell-runner

Deploy_Dev:
  stage: deploy
  needs: ["Test_Dev"]
  script:
    - docker pull $DOCKER_REGISTRY_IMAGE:dev.$CI_PIPELINE_ID
    - docker tag $DOCKER_REGISTRY_IMAGE:dev.$CI_PIPELINE_ID $DOCKER_REGISTRY_IMAGE:dev
    - docker push $DOCKER_REGISTRY_IMAGE:dev 
  tags:
    - shell-runner

###############################################
###               v3.3                     ###
###############################################

Build_33:
  stage: build
  script:
    - docker pull $DOCKER_REGISTRY_IMAGE:3.3  || true
    - docker build 
        --cache-from $DOCKER_REGISTRY_IMAGE:3.3
        --tag $DOCKER_REGISTRY_IMAGE:3.3.$CI_PIPELINE_ID 
        ./src/3.3
    - docker push $DOCKER_REGISTRY_IMAGE:3.3.$CI_PIPELINE_ID
  tags:
    - shell-runner

Test_33:
  stage: test
  needs: ["Build_33"]
  script:
    - docker pull $DOCKER_REGISTRY_IMAGE:3.3.$CI_PIPELINE_ID
    - docker ps
    - docker run -i -d --rm -e NEST_CONTAINER_MODE=nest-server -p 5000:5000  
        --name $CI_PIPELINE_ID $DOCKER_REGISTRY_IMAGE:3.3.$CI_PIPELINE_ID
    - docker ps
  tags:
    - shell-runner

Deploy_33:
  stage: deploy
  needs: ["Test_33"]
  script:
    - docker pull $DOCKER_REGISTRY_IMAGE:3.3.$CI_PIPELINE_ID
    - docker tag $DOCKER_REGISTRY_IMAGE:3.3.$CI_PIPELINE_ID $DOCKER_REGISTRY_IMAGE:3.3
    - docker push $DOCKER_REGISTRY_IMAGE:3.3
  tags:
    - shell-runner

###############################################
###               v3.2                      ###
###############################################

Build_32:
  stage: build
  script:
    - docker pull $DOCKER_REGISTRY_IMAGE:3.2  || true
    - docker build 
        --cache-from $DOCKER_REGISTRY_IMAGE:3.2
        --tag $DOCKER_REGISTRY_IMAGE:3.2.$CI_PIPELINE_ID 
        ./src/3.2
    - docker push $DOCKER_REGISTRY_IMAGE:3.2.$CI_PIPELINE_ID
  tags:
    - shell-runner

Test_32:
  stage: test
  needs: ["Build_32"]
  script:
    - docker pull $DOCKER_REGISTRY_IMAGE:3.2.$CI_PIPELINE_ID
    - docker ps
    - docker run -i -d --rm -e NEST_CONTAINER_MODE=nest-server -p 5000:5000  
        --name $CI_PIPELINE_ID $DOCKER_REGISTRY_IMAGE:3.2.$CI_PIPELINE_ID
    - docker ps
  tags:
    - shell-runner

Deploy_32:
  stage: deploy
  needs: ["Test_32"]
  script:
    - docker pull $DOCKER_REGISTRY_IMAGE:3.2.$CI_PIPELINE_ID
    - docker tag $DOCKER_REGISTRY_IMAGE:3.2.$CI_PIPELINE_ID $DOCKER_REGISTRY_IMAGE:3.2
    - docker push $DOCKER_REGISTRY_IMAGE:3.2
  tags:
    - shell-runner

###############################################
###               v3.1                      ###
###############################################

Build_31:
  stage: build
  when: manual
  script:
    - docker pull $DOCKER_REGISTRY_IMAGE:3.1  || true
    - docker build 
        --cache-from $DOCKER_REGISTRY_IMAGE:3.1
        --tag $DOCKER_REGISTRY_IMAGE:3.1.$CI_PIPELINE_ID 
        ./src/3.1
    - docker push $DOCKER_REGISTRY_IMAGE:3.1.$CI_PIPELINE_ID
  tags:
    - shell-runner

Test_31:
  stage: test
  needs: ["Build_31"]
  script:
    - docker pull $DOCKER_REGISTRY_IMAGE:3.1.$CI_PIPELINE_ID
    - docker ps
    - docker run -i -d --rm -e NEST_CONTAINER_MODE=nest-server -p 5000:5000  
        --name $CI_PIPELINE_ID $DOCKER_REGISTRY_IMAGE:3.1.$CI_PIPELINE_ID
    - docker ps
  tags:
    - shell-runner

Deploy_31:
  stage: deploy
  needs: ["Test_31"]
  script:
    - docker pull $DOCKER_REGISTRY_IMAGE:3.1.$CI_PIPELINE_ID
    - docker tag $DOCKER_REGISTRY_IMAGE:3.1.$CI_PIPELINE_ID $DOCKER_REGISTRY_IMAGE:3.1
    - docker push $DOCKER_REGISTRY_IMAGE:3.1
  tags:
    - shell-runner

###############################################
###               v3.0                      ###
###############################################

Build_30:
  stage: build
  when: manual
  script:
    - docker pull $DOCKER_REGISTRY_IMAGE:3.0  || true
    - docker build 
        --cache-from $DOCKER_REGISTRY_IMAGE:3.0
        --tag $DOCKER_REGISTRY_IMAGE:3.0.$CI_PIPELINE_ID 
        ./src/3.0
    - docker push $DOCKER_REGISTRY_IMAGE:3.0.$CI_PIPELINE_ID
  tags:
    - shell-runner

Test_30:
  stage: test
  needs: ["Build_30"]
  script:
    - docker pull $DOCKER_REGISTRY_IMAGE:3.0.$CI_PIPELINE_ID
    - docker ps
    - docker run -i -d --rm -e NEST_CONTAINER_MODE=nest-server -p 5000:5000  
        --name $CI_PIPELINE_ID $DOCKER_REGISTRY_IMAGE:3.0.$CI_PIPELINE_ID
    - docker ps
  tags:
    - shell-runner

Deploy_30:
  stage: deploy
  needs: ["Test_30"]
  script:
    - docker pull $DOCKER_REGISTRY_IMAGE:3.0.$CI_PIPELINE_ID
    - docker tag $DOCKER_REGISTRY_IMAGE:3.0.$CI_PIPELINE_ID $DOCKER_REGISTRY_IMAGE:3.0
    - docker push $DOCKER_REGISTRY_IMAGE:3.0
  tags:
    - shell-runner

###############################################
###               v2.20.2                   ###
###############################################

Build_2202:
  stage: build
  when: manual
  script:
    - docker pull $DOCKER_REGISTRY_IMAGE:2.20.2  || true
    - docker build 
        --cache-from $DOCKER_REGISTRY_IMAGE:2.20.2  
        --tag $DOCKER_REGISTRY_IMAGE:2.20.2.$CI_PIPELINE_ID 
        ./src/3.1
    - docker push $DOCKER_REGISTRY_IMAGE:2.20.2.$CI_PIPELINE_ID
  tags:
    - shell-runner

Test_2202:
  stage: test
  needs: ["Build_2202"]
  script:
    - docker rm -f $(docker ps -a -q)
    - docker container prune
    - docker pull $DOCKER_REGISTRY_IMAGE:2.20.2.$CI_PIPELINE_ID
    - docker ps
    - docker run -i -d --rm -e NEST_CONTAINER_MODE=nest-server -p 5000:5000  
        --name $CI_PIPELINE_ID $DOCKER_REGISTRY_IMAGE:2.20.2.$CI_PIPELINE_ID
    - docker ps
  tags:
    - shell-runner

Deploy_2202:
  stage: deploy
  needs: ["Test_2202"]
  script:
    - docker pull $DOCKER_REGISTRY_IMAGE:2.20.2.$CI_PIPELINE_ID
    - docker tag $DOCKER_REGISTRY_IMAGE:2.20.2.$CI_PIPELINE_ID $DOCKER_REGISTRY_IMAGE:2.20.2
    - docker push $DOCKER_REGISTRY_IMAGE:2.20.2
  tags:
    - shell-runner

###############################################
###               v2.18.0                   ###
###############################################

Build_2180:
  stage: build
  when: manual
  script:
    - docker pull $DOCKER_REGISTRY_IMAGE:2.18.0  || true
    - docker build 
        --cache-from $DOCKER_REGISTRY_IMAGE:2.18.0  
        --tag $DOCKER_REGISTRY_IMAGE:2.18.0.$CI_PIPELINE_ID 
        ./src/3.1
    - docker push $DOCKER_REGISTRY_IMAGE:2.18.0.$CI_PIPELINE_ID
  tags:
    - shell-runner

Test_2180:
  stage: test
  needs: ["Build_2180"]
  script:
    - docker rm -f $(docker ps -a -q)
    - docker container prune
    - docker pull $DOCKER_REGISTRY_IMAGE:2.18.0.$CI_PIPELINE_ID
    - docker ps
    - docker run -i -d --rm -e NEST_CONTAINER_MODE=nest-server -p 5000:5000  
        --name $CI_PIPELINE_ID $DOCKER_REGISTRY_IMAGE:2.18.0.$CI_PIPELINE_ID
    - docker ps
  tags:
    - shell-runner

Deploy_2180:
  stage: deploy
  needs: ["Test_2180"]
  script:
    - docker pull $DOCKER_REGISTRY_IMAGE:2.18.0.$CI_PIPELINE_ID
    - docker tag $DOCKER_REGISTRY_IMAGE:2.18.0.$CI_PIPELINE_ID $DOCKER_REGISTRY_IMAGE:2.18.0
    - docker push $DOCKER_REGISTRY_IMAGE:2.18.0
  tags:
    - shell-runner

###############################################
###               v2.16.0                   ###
###############################################

Build_2160:
  stage: build
  when: manual
  script:
    - docker pull $DOCKER_REGISTRY_IMAGE:2.16.0  || true
    - docker build 
        --cache-from $DOCKER_REGISTRY_IMAGE:2.16.0  
        --tag $DOCKER_REGISTRY_IMAGE:2.16.0.$CI_PIPELINE_ID 
        ./src/3.1
    - docker push $DOCKER_REGISTRY_IMAGE:2.16.0.$CI_PIPELINE_ID
  tags:
    - shell-runner

Test_2160:
  stage: test
  needs: ["Build_2160"]
  script:
    - docker rm -f $(docker ps -a -q)
    - docker container prune
    - docker pull $DOCKER_REGISTRY_IMAGE:2.16.0.$CI_PIPELINE_ID
    - docker ps
    - docker run -i -d --rm -e NEST_CONTAINER_MODE=nest-server -p 5000:5000  
        --name $CI_PIPELINE_ID $DOCKER_REGISTRY_IMAGE:2.16.0.$CI_PIPELINE_ID
    - docker ps
  tags:
    - shell-runner

Deploy_2160:
  stage: deploy
  needs: ["Test_2160"]
  script:
    - docker pull $DOCKER_REGISTRY_IMAGE:2.16.0.$CI_PIPELINE_ID
    - docker tag $DOCKER_REGISTRY_IMAGE:2.16.0.$CI_PIPELINE_ID $DOCKER_REGISTRY_IMAGE:2.16.0
    - docker push $DOCKER_REGISTRY_IMAGE:2.16.0
  tags:
    - shell-runner

###############################################
###               v2.14.0                   ###
###############################################

Build_2140:
  stage: build
  when: manual
  script:
    - docker pull $DOCKER_REGISTRY_IMAGE:2.14.0  || true
    - docker build 
        --cache-from $DOCKER_REGISTRY_IMAGE:2.14.0  
        --tag $DOCKER_REGISTRY_IMAGE:2.14.0.$CI_PIPELINE_ID 
        ./src/3.1
    - docker push $DOCKER_REGISTRY_IMAGE:2.14.0.$CI_PIPELINE_ID
  tags:
    - shell-runner

Test_2140:
  stage: test
  needs: ["Build_2140"]
  script:
    - docker rm -f $(docker ps -a -q)
    - docker container prune
    - docker pull $DOCKER_REGISTRY_IMAGE:2.14.0.$CI_PIPELINE_ID
    - docker ps
    - docker run -i -d --rm -e NEST_CONTAINER_MODE=nest-server -p 5000:5000  
        --name $CI_PIPELINE_ID $DOCKER_REGISTRY_IMAGE:2.14.0.$CI_PIPELINE_ID
    - docker ps
  tags:
    - shell-runner

Deploy_2140:
  stage: deploy
  needs: ["Test_2140"]
  script:
    - docker pull $DOCKER_REGISTRY_IMAGE:2.14.0.$CI_PIPELINE_ID
    - docker tag $DOCKER_REGISTRY_IMAGE:2.14.0.$CI_PIPELINE_ID $DOCKER_REGISTRY_IMAGE:2.14.0
    - docker push $DOCKER_REGISTRY_IMAGE:2.14.0
  tags:
    - shell-runner

###############################################
###               v2.12.0                   ###
###############################################

Build_2120:
  stage: build
  when: manual
  script:
    - docker pull $DOCKER_REGISTRY_IMAGE:2.12.0  || true
    - docker build 
        --cache-from $DOCKER_REGISTRY_IMAGE:2.12.0  
        --tag $DOCKER_REGISTRY_IMAGE:2.12.0.$CI_PIPELINE_ID 
        ./src/3.1
    - docker push $DOCKER_REGISTRY_IMAGE:2.12.0.$CI_PIPELINE_ID
  tags:
    - shell-runner

Test_2120:
  stage: test
  needs: ["Build_2120"]
  script:
    - docker rm -f $(docker ps -a -q)
    - docker container prune
    - docker pull $DOCKER_REGISTRY_IMAGE:2.12.0.$CI_PIPELINE_ID
    - docker ps
    - docker run -i -d --rm -e NEST_CONTAINER_MODE=nest-server -p 5000:5000  
        --name $CI_PIPELINE_ID $DOCKER_REGISTRY_IMAGE:2.12.0.$CI_PIPELINE_ID
    - docker ps
  tags:
    - shell-runner

Deploy_2120:
  stage: deploy
  needs: ["Test_2120"]
  script:
    - docker pull $DOCKER_REGISTRY_IMAGE:2.12.0.$CI_PIPELINE_ID
    - docker tag $DOCKER_REGISTRY_IMAGE:2.12.0.$CI_PIPELINE_ID $DOCKER_REGISTRY_IMAGE:2.12.0
    - docker push $DOCKER_REGISTRY_IMAGE:2.12.0
  tags:
    - shell-runner
