# do not use "latest" here, if you want this to work in the future
default:
  image: ubuntu:22.04
  tags:
    - shell-runner

stages:
  - build
  - test
  - deploy

before_script:
  - echo -n $DOCKER_REGISTRY_TOKEN | docker login -u $DOCKER_REGISTRY_USER --password-stdin $DOCKER_REGISTRY
  - echo -n $DOCKERHUB_REGISTRY_TOKEN | docker login -u $DOCKERHUB_REGISTRY_USER --password-stdin

include: 'ci-templates/*.yml'










