name: Docker Images CI

on:
  pull_request:
    branches: [ master ]
  pull_request_target:
    branches: [ master ]
  push:
    branches: [ master ]
  workflow_dispatch:

jobs:
  build-dev:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Build DEV Docker image
        run: |
          docker build ./src/dev \
            --tag nest/nest-simulator:latest \
            --tag nest/nest-simulator:dev

      - name: Check NEST dev
        run: |
          docker run --rm nest/nest-simulator:latest python3 -c "import nest" | grep "Version:"

      - name: Login to Docker Hub
        if: ${{ (github.event_name == 'push' || github.event_name == 'workflow_dispatch') && github.ref == 'refs/heads/master' }}
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

      - name: Push DEV to Docker Hub
        if: ${{ (github.event_name == 'push' || github.event_name == 'workflow_dispatch') && github.ref == 'refs/heads/master' }}
        run: |
          docker push nest/nest-simulator:latest
          docker push nest/nest-simulator:dev

  build-2-20-2:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Build 2.20.2 Docker image
        run: |
          docker build ./src/2.20.2 --tag nest/nest-simulator:2.20.2

      - name: Check NEST 2.20.2
        run: |
          docker run --rm nest/nest-simulator:2.20.2 python3 -c "import nest" | grep "Version:"

      - name: Login to Docker Hub
        if: ${{ (github.event_name == 'push' || github.event_name == 'workflow_dispatch') && github.ref == 'refs/heads/master' }}
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

      - name: Push 2.20.2 to Docker Hub
        if: ${{ (github.event_name == 'push' || github.event_name == 'workflow_dispatch') && github.ref == 'refs/heads/master' }}
        run: |
          docker push nest/nest-simulator:2.20.2

  build-3-9:

    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Build 3.9 Docker image
        run: |
          docker build ./src/3.9 --tag nest/nest-simulator:3.9

      - name: Check NEST 3.9
        run: |
          docker run --rm nest/nest-simulator:3.9 python3 -c "import nest" | grep "Version:"

      - name: Login to Docker Hub
        if: ${{ (github.event_name == 'push' || github.event_name == 'workflow_dispatch') && github.ref == 'refs/heads/master' }}
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

      - name: Push 3.9 to Docker Hub
        if: ${{ (github.event_name == 'push' || github.event_name == 'workflow_dispatch') && github.ref == 'refs/heads/master' }}
        run: |
          docker push nest/nest-simulator:3.9


