name: Mirror to EBRAINS

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  sync_to_ebrains:
    runs-on: ubuntu-latest
    if: ${{ github.repository_owner == 'nest' }}
    steps:
      - name: sycnmaster
        uses: wei/git-sync@v3
        with:
          source_repo: "nest/nest-docker"
          source_branch: "master"
          destination_repo: "https://ghpusher:${{ secrets.EBRAINS_PUSH_TOKEN }}@gitlab.ebrains.eu/nest/nest-docker.git"
          destination_branch: "master"
      - name: synctags
        uses: wei/git-sync@v3
        with:
          source_repo: "nest/nest-simulator"
          source_branch: "refs/tags/*"
          destination_repo: "https://ghpusher:${{ secrets.EBRAINS_PUSH_TOKEN }}@gitlab.ebrains.eu/nest/nest-docker.git"
          destination_branch: "refs/tags/*"
